### ISSUE TITLE
Appending header causes exception in ktor 0.9.1

### ISSUE THREAD

**Issue by mantono** [zensum/ktor-prometheus-feature#5]
This causes an exception in version 0.9.1 of Ktor https://github.com/zensum/ktor-prometheus-feature/blob/abaa1260f77939b8776031e798b78fed5c20933c/src/main/kotlin/se/zensum/ktorPrometheusFeature/PrometheusResponder.kt#L33

> **io.ktor.response.UnsafeHeaderException: Header Content-Type is controlled by the engine and cannot be set explicitly**
    at io.ktor.response.ResponseHeaders.append(ResponseHeaders.kt:17)
    at io.ktor.response.ResponseHeaders.append$default(ResponseHeaders.kt:15)
    at io.ktor.server.engine.BaseApplicationResponse$commitHeaders$2.invoke(BaseApplicationResponse.kt:59)
    at io.ktor.server.engine.BaseApplicationResponse$commitHeaders$2.invoke(BaseApplicationResponse.kt:15)
    at io.ktor.util.StringValuesKt$sam$BiConsumer$6fcc60f7.accept(StringValues.kt)
    at io.ktor.org.apache.commons.collections4.map.AbstractLinkedMap.forEach(AbstractLinkedMap.java:163)
    at io.ktor.util.StringValuesImpl.forEach(StringValues.kt:111)
    at io.ktor.server.engine.BaseApplicationResponse.commitHeaders(BaseApplicationResponse.kt:47)
    at io.ktor.server.engine.BaseApplicationResponse.respondOutgoingContent$suspendImpl(BaseApplicationResponse.kt:109)
    at io.ktor.server.engine.BaseApplicationResponse.respondOutgoingContent(BaseApplicationResponse.kt)
    at io.ktor.server.netty.NettyApplicationResponse.respondOutgoingContent$suspendImpl(NettyApplicationResponse.kt:34)
    at io.ktor.server.netty.NettyApplicationResponse.respondOutgoingContent(NettyApplicationResponse.kt)
    at io.ktor.server.engine.BaseApplicationResponse$$special$$inlined$apply$lambda$1.doResume(BaseApplicationResponse.kt:34)
    at io.ktor.server.engine.BaseApplicationResponse$$special$$inlined$apply$lambda$1.invoke(BaseApplicationResponse.kt)
    at io.ktor.server.engine.BaseApplicationResponse$$special$$inlined$apply$lambda$1.invoke(BaseApplicationResponse.kt:15)
    at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
    at io.ktor.pipeline.PipelineContext.proceedWith(PipelineContext.kt:35)
    at io.ktor.server.engine.DefaultTransformKt$installDefaultTransformations$1.doResume(DefaultTransform.kt:15)
    at io.ktor.server.engine.DefaultTransformKt$installDefaultTransformations$1.invoke(DefaultTransform.kt)
    at io.ktor.server.engine.DefaultTransformKt$installDefaultTransformations$1.invoke(DefaultTransform.kt)
    at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
    at io.ktor.pipeline.Pipeline.execute(Pipeline.kt:22)
    at se.zensum.ktorPrometheusFeature.PrometheusFeature.intercept(prometheusFeature.kt:84)
    at se.zensum.ktorPrometheusFeature.PrometheusFeature$Feature$install$1.doResume(prometheusFeature.kt:75)
    at se.zensum.ktorPrometheusFeature.PrometheusFeature$Feature$install$1.invoke(prometheusFeature.kt)
    at se.zensum.ktorPrometheusFeature.PrometheusFeature$Feature$install$1.invoke(prometheusFeature.kt:69)

Will try to remove it and verify that this feature still works as intended.

**Comment by mantono** [comment]
Fixed in 1b96f86
